//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapBK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BangKeDS2019Entities : DbContext
    {
        public BangKeDS2019Entities()
            : base("name=BangKeDS2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BK_DiaBan> BK_DiaBan { get; set; }
        public virtual DbSet<BK_Ho> BK_Ho { get; set; }
        public virtual DbSet<BK_Thon> BK_Thon { get; set; }
        public virtual DbSet<DM_Huyen> DM_Huyen { get; set; }
        public virtual DbSet<DM_Tinh> DM_Tinh { get; set; }
        public virtual DbSet<DM_TrangThaiDiaBan> DM_TrangThaiDiaBan { get; set; }
        public virtual DbSet<DM_Xa> DM_Xa { get; set; }
        public virtual DbSet<QL_ThongTinDiaBan> QL_ThongTinDiaBan { get; set; }
        public virtual DbSet<QT_DanhSachChucNang> QT_DanhSachChucNang { get; set; }
        public virtual DbSet<QT_NguoiDung> QT_NguoiDung { get; set; }
        public virtual DbSet<QT_NhomNguoiDung> QT_NhomNguoiDung { get; set; }
        public virtual DbSet<QT_PhanQuyen> QT_PhanQuyen { get; set; }
        public virtual DbSet<QT_SystemLog> QT_SystemLog { get; set; }
        public virtual DbSet<Tam_TongHopTienDo> Tam_TongHopTienDo { get; set; }
        public virtual DbSet<TMP_BangKeHo> TMP_BangKeHo { get; set; }
    }
}
