//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapBK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DM_Xa
    {
        public string MaTinh { get; set; }
        public string MaHuyen { get; set; }
        [Key]
        public string MaXa { get; set; }
        public string TenXa { get; set; }
        public int TTNT { get; set; }
        public string Xa { get; set; }
        public string Phuong { get; set; }
        public string ThiTran { get; set; }
    }
}
