//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapBK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_ThongTinDiaBan
    {
        public int Id { get; set; }
        public string MaTinh { get; set; }
        public string MaHuyen { get; set; }
        public string MaXa { get; set; }
        public string MaThon { get; set; }
        public string MaDiaBan { get; set; }
        public Nullable<int> TongSoNha { get; set; }
        public Nullable<int> TongSoHo { get; set; }
        public Nullable<int> SoHoWebForm { get; set; }
        public Nullable<int> SoHoMau { get; set; }
        public Nullable<int> TongSoNguoi { get; set; }
        public Nullable<int> TongSoNu { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
    }
}
