//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapBK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QT_PhanQuyen
    {
        public string MaNhom { get; set; }
        public int MaChucNang { get; set; }
        public Nullable<bool> ActiveView { get; set; }
        public Nullable<bool> ActiveEdit { get; set; }
        public Nullable<bool> ActivePrint { get; set; }
        public Nullable<bool> ActiveAll { get; set; }
    }
}
