//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapBK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_BangKeHo
    {
        public System.Guid Id { get; set; }
        public string MaTinh { get; set; }
        public string MaHuyen { get; set; }
        public string MaXa { get; set; }
        public string MaThon { get; set; }
        public string MaDiaBan { get; set; }
        public int TTNT { get; set; }
        public string SttNha { get; set; }
        public string SttHo { get; set; }
        public string TenTinh { get; set; }
        public string TenHuyen { get; set; }
        public string TenXa { get; set; }
        public string TenThon { get; set; }
        public string TenDiaBan { get; set; }
        public string TenChuHo { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public int TongSoNguoi { get; set; }
        public int TongSoNu { get; set; }
        public bool IsWebForm { get; set; }
        public string GhiChu { get; set; }
    }
}
